blank_issues_enabled: false

contact_links:
  - name: AppsFlyer Support (Customer Assistant Chatbot)
    url: https://support.appsflyer.com/hc/en-us/articles/23583984402193-Using-the-Customer-Assistant-Chatbot
    about: For the fastest and most effective support, please contact the AppsFlyer support team using the Customer Assistant Chatbot. 
