
platform :ios, '9.0'

pre_install do |installer|
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

target 'DemoPod2' do
  pod 'React', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTImage',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTNetwork',
    'RCTText',
    'RCTSettings',
    'RCTActionSheet',
    'RCTVibration',
    'RCTPushNotification',
    'RCTWebSocket' # needed for debugging
  ], path: '../node_modules/react-native'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  #pod 'react-native-blur', path: '../node_modules/react-native-blur'
  #pod 'BugsnagReactNative', path: '../node_modules/bugsnag-react-native'
  #pod 'RNI18n', path: '../node_modules/react-native-i18n'
  #pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  #pod 'pushwoosh-react-native-plugin', path: '../node_modules/pushwoosh-react-native-plugin'
  #pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  #pod 'Fabric'
  #pod 'Crashlytics'
  #pod 'react-native-appsflyer', path: '../node_modules/react-native-appsflyer'
  #pod 'react-native-google-analytics-bridge', path: '../node_modules/react-native-google-analytics-bridge'
  #pod 'Mixpanel'


  pod 'react-native-appsflyer',:path => '../node_modules/react-native-appsflyer'

  end
