name: Build React-Native and Expo apps with AppsFlyer plugin
#                                          /--> rn --> build android
#                                         /---> rn --> build ios
# --> Install plugin on rn and expo apps 
#                                        \---> expo --> build android
#                                         \--> expo --> build ios
on: [pull_request, push]

jobs:
  install-plugin-Expo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install AppsFlyer on an expo app
      run: cd demos/appsflyer-expo-app && yarn install && yarn add ../../ --save

  install-plugin-RN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install AppsFlyer on an React-Native app
      run: cd demos/appsflyer-react-native-app && yarn install && yarn add ../../ --save

  build-RN-android:
    needs: install-plugin-RN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print files
      run: cd demos/appsflyer-react-native-app && ls
    - name: Build Android RN app
      run: echo 'RN android'

  build-RN-ios:
    needs: install-plugin-RN
    runs-on: macos-latest
    steps:
    - name: Build iOS RN app
      run: echo 'RN iOS'
  
  build-Expo-android:
    needs: install-plugin-Expo
    runs-on: ubuntu-latest
    steps:
    - name: Build Android Expo app
      run: echo 'expo android'

  build-Expo-ios:
    needs: install-plugin-Expo
    runs-on: macos-latest
    steps:
    - name: Build iOS Expo app
      run: echo 'expo ios'