# This workflow triggers the org-wide reusable workflow to close inactive issues on a schedule
on:
  schedule:
    - cron: "0 10 * * *" # Runs daily at 10:00 UTC
  workflow_dispatch:

jobs:
  close-issues:
    uses: AppsFlyerSDK/github-common-workflow-and-template/.github/workflows/close_inactive_issues.yml@main
    secrets: inherit 