name: Deploy To QA

on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The branch: $BRANCH"
        env:
          BRANCH: ${{ github.event.inputs.branch }}
