on: 
  push:
    # inputs:
    #   branch:
    #     description: 'Branch to deploy'     
    #     required: true
    #     default: '' 
    #     type: choice
    #     options:
    #     - info
    #     - warning
    #     - debug 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The branch: $BRANCH"
        env:
          BRANCH: ${{ github }}