name: Pre-release workflow
#                                          /--> rn --> build android
#                                         /---> rn --> build ios
# --> Install plugin on rn and expo apps 
#                                        \---> expo --> build android
#                                         \--> expo --> build ios

on:
  push:
    branches:
      - 'releases/*/*/*'
  pull_request:
    branches:
      - master
jobs:
  Run-Unit-Tests:
    uses: ./.github/workflows/unit-tests-workflow.yml

  Build-Sample-Apps:
    uses: ./.github/workflows/build-workflow.yml

  Deploy-To-QA:
    if: github.ref == 'releases/*/*/*'
    needs: [Build-Sample-Apps, Run-Unit-Tests]
    uses: ./.github/workflows/deploy-QA.yml