name: Pre-release workflow

on:
  push:
    branches:
      - releases/[0-9].x.x/[0-9].[0-9].x/[0-9].[0-9].[0-9]+-rc[0-9]+

jobs:
  Run-Unit-Tests:
    uses: ./.github/workflows/unit-tests-workflow.yml

  Build-Sample-Apps:
    uses: ./.github/workflows/build-workflow.yml

  Deploy-To-QA:
    needs: [Build-Sample-Apps, Run-Unit-Tests]
    uses: ./.github/workflows/deploy-QA.yml