name: Release plugin to QA

on:
  push:
    branches:
      - releases/[0-9].x.x/[0-9].[0-9].x/[0-9].[0-9].[0-9]+-rc[0-9]+

jobs:
  Run-Unit-Tests:
    uses: ./.github/workflows/unit-tests-workflow.yml

  Build-Sample-Apps:
    uses: ./.github/workflows/build-apps-workflow.yml
    secrets: inherit
    
  Deploy-To-QA:
    needs: [Run-Unit-Tests, Build-Sample-Apps]
    uses: ./.github/workflows/deploy-to-QA.yml
    secrets: inherit